---
- name: "Installing packages for {{ _apache_package_name }}"
  ansible.builtin.package:
    name: "{{ _apache_packages }}"
    state: present

- name: "Checking service state of {{ _apache_package_name }}"
  ansible.builtin.systemd:
    name: "{{ _apache_package_name }}"
    state: "{{ apache_service_state }}"
    enabled: "{{ apache_service_enabled }}"
