---
- name: "Gather OS specific variables"
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro }}.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: "Include tasks for install"
  ansible.builtin.include_tasks: install.yml
  tags: apache_install

- name: "Include tasks for mpm"
  ansible.builtin.include_tasks: mpm.yml
  tags: apache_mpm

- name: "Include tasks for mods"
  ansible.builtin.include_tasks: mods.yml
  tags: apache_mods

- name: "Include tasks for conf"
  ansible.builtin.include_tasks: conf.yml
  tags: apache_conf

- name: "Include tasks for default vhost"
  ansible.builtin.include_tasks: default_vhost.yml
  tags: apache_default_vhost
  when: not apache_remove_default_vhost

- name: "Remove default vhost config file"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ _apache_vhost_conf_path }}/000-default.conf"
    - "/etc/{{ _apache_package_name }}/sites-enabled/000-default.conf"
  when: apache_remove_default_vhost

- name: "Include tasks for vhosts"
  ansible.builtin.include_tasks: vhosts.yml
  vars:
    _apache_vhost: "{{ apache_vhosts_default | combine(item) }}"
  loop: "{{ apache_vhosts }}"
  loop_control:
    label: "Config virtual host {{ item.name }}"
  tags: apache_vhosts
  when: apache_vhosts | length > 0

- name: Create custom apache2 systemd service
  ansible.builtin.template:
    src: "{{ apache_systemd_unit_template }}"
    dest: "{{ apache_systemd_base_path }}/{{ _apache_package_name }}.service"
    owner: root
    group: root
    mode: 0644
    force: true
  notify:
    - Reload apache daemon
    - Restart apache
  when: apache_manage_systemd_override
